### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by riccardobl** [riccardobl/jme3-bullet-builder#1]
- [x] Improved build system
- [ ] Build for android
- [ ] Keep going if one or more versions fail.
- [ ] Add way to specify which version to build, so that only repos that have changed are built.
